### ISSUE TITLE
[Web UX] The logout button is counter-intuitive

### ISSUE THREAD

**Issue by djalilhebal** [WietseWind/xrptipbot#11]
Just learned of this cool project and literally just started checking it out... but I've a couple remarks:

- I expect clicking on my avatar to take me to my account (www.xrptipbot.com/account), not to log me out!
- Only clicking on the "logout" text should log me out. Not the hidden box, not my avatar, only the text.

> ![border-color-red](https://user-images.githubusercontent.com/32184973/68884690-f7b79c80-0713-11ea-8159-c951eca61fd4.png)
> This screenshot taken when hovering over the red box in the middle / Plus, a `border: 3px solid red;` CSS rule was applied to each of the three elements.

**Comment by WietseWind** [comment]
Thank you! I just applied a really ugly quick fix, and I'll make sure to get a better design ASAP ;)
