### ISSUE TITLE
Discord integration

### ISSUE THREAD

**Issue by scragz** [WietseWind/xrptipbot#2]
Would be so cool to be able to tip zerps on Discord!

We have been looking at getting a tip bot going on the Ripple Discord and figured we should reach out about Discord integration before we duplicate a bunch of the work you already did. Since you already have the infrastructure setup with the wallets and everything and the bot already running for reddit and twitter.

**Comment by WietseWind** [comment]
@scragz Nice! Are you the admin of the Discord group? If there are any admins with relevant Discord groups I'd be happy to add a Discord 'network' to the tipbot, or at least share some info, merge, etc.!

**Comment by WietseWind** [comment]
@scragz Fixed :) Have one of the admins enable the bot using this URL:
https://xrptipbot.nodum.io/botauth/discord
