### ISSUE TITLE
Use of a username from a deleted Twitter account.

### ISSUE THREAD

**Issue by David-projects** [WietseWind/xrptipbot#5]
Hi

Not sure if this is a bug or not but this is what I found

I had a Twitter username @FireAndIce1505, I had 3 XRP that had been tipped to me.
I deleted my twitter account without moving my XRP from tipbot
About 1 to 2 months later I created a new Twitter account and changed my username back to @FireAndIce1505 and then logged into tipbot and found my tips still there.

Questions, if someone else had used that Twitter username and tried to log into the account would I have lost all the tips? 
in which case, if people change there Twitter account would they lose their tips? 

Thanks 

@FireAndIce1505

**Comment by WietseWind** [comment]
Hey!

Thanks for your message. If you change your handle, the TipBot offers you to migrate the balance:
https://twitter.com/WietseWind/status/1007284909696790529

However, if you remove your account without withdrawing your balance first, that's user error imo. If someone else would register that handle, then yes: indeed: they could get your balance. So: withdraw before deleting your account, or migrate balance after changing your account handle ;)

👋 
Wietse
