### ISSUE TITLE
Xrp tipbot 

### ISSUE THREAD

**Issue by Spanysh37** [WietseWind/xrptipbot#8]
My tipbot isn't sending out tips when I tip. I'm entering the format correctly for not responding to a tweet " Hello @spanysh_fli + 20 @xrptipbot " but the bot never sends out my tip

**Comment by WietseWind** [comment]
Where are you sending the tips? If Twitter / Reddit / Discord: Can you please link to the message?

**Comment by Spanysh37** [comment]
I'm sending the tip on twitter

**Comment by Spanysh37** [comment]
[image: Screen Shot 2018-12-23 at 9.56.45 PM.png]
Sorry wrong attachment on the first email

**Comment by WietseWind** [comment]
Please send me a link to the Tweet.

**Comment by Spanysh37** [comment]
https://twitter.com/Spanysh_FLi/status/1077037457978347521

Heres the link sorry I misunderstood what you were asking me to do.

**Comment by WietseWind** [comment]
Your tweets are private. The Tipbot cannot see your tweets. It only works for public tweeting accounts.
